apiVersion: v1
kind: Service
metadata:
  labels:
    env: production
    app: testcoreapp
  name: testcoreapp-canary
  namespace: production
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: {{name}}
  type: NodePort
