apiVersion: v1
kind: Service
metadata:
  labels:
    env: production
    app: testcoreapp
    track: stable
  name: testcoreapp
  namespace: production
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    env: production
    app: testcoreapp
    track: stable
  type: NodePort
