apiVersion: v1
kind: Service
metadata:
  labels:
    env: {{envType}}
    app: {{name}}
  name: {{name}}
  namespace: {{namespace}}
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: {{app}}
  type: LoadBalancer
