apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-addon: ingress-nginx.addons.k8s.io
  name: {{name}}
  namespace: {{namespace}}
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: {{app}}
  type: LoadBalancer
